### ISSUE TITLE
Certain constraints are never evaluated

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon-ibex#248] opened 2017-10-17 15:16 UTC
Where does this happen? -> CompanyToIT.gen.SimpleModelgenTest->testAdmin

---

What happens? -> Contraints are not evaluated as long as a certain constraint is not commented out

---

The problematic rule is called AdminToRouter from CompanyToIT.
Defining the condition eq_string(it.name, network.name) leads to the problem that conditions are no longer evaluated (their corresponding TGGNativeOperations are no longer called)
However, I went over all Constraints and defined operations which are registered in DemoclesEngine::line:456 and it looks correct. (Also the adornments).
After defining it, the TGGAttributeNativeOperation.getDataFrame operation is never called again.

**Comment by gervarro** [comment] 2017-11-17 14:30
Hi Lars,

could you please check whether the attribute lookup constraints are properly produced in the ibexToDemocles methods? For example the pattern `EmployeeToPCRule__GEN` contains only a pattern invocation constraint and a TGG attribute constraint (`eq_string(__foo___name:EString,__bar___name:EString`), but the attribute lookup constraints are missing (`name(foo:EObject, __foo___name:EString)`). If the TGG attribute constraint parameters are not connected to the regular EObject variables, then a disconnected pattern is produced resulting in a "No search plan exists" exception.

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-11-17 15:03
Hi Greg,

this is an interesting point; I just discussed a bit with Lars.
Attached you can find a simplified EmployeeToPCRule that nonetheless explains what the "problem" is.

The point is that we sometimes have to determine attribute values **without** connecting them to any EObjects as they do not exist yet.  In this case the Employee and PC are to be created, but their names are to be "matched" on the LHS.  This should be possible because we have an equal constraint with a FF adornment, i.e., we have an operation that can generate a pair of consistent but random values. 

In the part that takes care of "green" patterns we then extract these attribute values and connect them ourselves to the newly generated Employee and PC as required.

One could perhaps think that this is unnecessary - so why not just remove the constraint completely?  The problem is that this is often impossible -- there might be some connection to other attribute values that are connected to EObjects.  Another point is that if the LHS is disconnected or not depends on the operationalisation (fwd and bwd will not be disconnected). 

Is it possible to support such disconnected cases?  I was hoping for this as it is also possible to pattern match multiple disconnected nodes.

Cheers,
Tony

P.S:  If this is a huge problem we can of course remove all FFF* cases and somehow handle them specially in the code dealing with green patterns.

![2017-11-17 15 53 51](https://user-images.githubusercontent.com/6302793/32953266-f66695ee-cbaf-11e7-88c6-0907bcc0d0ea.jpg)

**Comment by gervarro** [comment] 2017-11-18 16:00
Hi Tony,

handling disjoint patterns is not a problem in itself, but randomly generated information might cause problems in an incremental setup due to two reasons:

1. The pattern matcher does not maintain explicit tracing information between the partial matches. Let us suppose that a pattern `P(A,B,CName,DName)` is given, and the structural partial match is `(a,b)` and the randomly generated String based partial match is `(c1,d1)`, the complete match is then `(a,b,c1,d1)` as expected, and this match is stored in the memory (but no information that `(a,b,c1,d1)` was derived from `(a,b)` and `(c1,d1)`). If the structural part `(a,b)` is deleted due to any reasons in the future, the TGG attribute constraint operation should be able to create exactly `(c1,d1)` as response (most probably even without having access to the other fields `(a,b)` in the partial match), otherwise the pattern matcher could not eliminate the match `(a,b,c1,d1)`.
2. Patterns with disjoint component follow a cross-join semantics, namely, in case of structural matches `(a1,b1)` and `(a2,b2)` and text matches `(c1,d1)` and `(c2,d2)`, the end result contains all the 4 combinations, and I guess this is not what you would expect in this case.

Disjoint structural patterns without randomness should not be a problem for the pattern matcher.

I would probably distinguish between those cases when the attribute constraints are or are not connected to the structural part. If the attribute constraint is connected to the structural part, then I would handle it in the black pattern. If the attribute constraint is disjoint completely from the structural part, then I would put it into the green pattern. I would guess that disjoint attribute constraints do not have the role to restrict/filter the set of matches. Note that the current Democles code base (see the usage of the `UnionFind` class) already supports the decision on compoundness, and a batch interpreted pattern matcher could also be set up for green patterns relatively easily. (There might be few cases, when the compoundness analysis (which uses constraints without adornment) says that the pattern is compound, but the search plan algorithm cannot find a valid search plan due to specially selected adornment setups.)

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-11-19 16:23
Hi Greg,

I’ve discussed this with Lars and we would suggest handling these cases just like disjoint patterns for the moment.  

When we eventually have tests that fail due to (1) or (2) then we’ll think of something.  The general solution will require a batch interpreter as you say as the set of detached attribute constraints can be arbitrarily complex and require a search plan.

Our hope is just to have something that works for most cases and can be merged ASAP into master.   We have a _lot_ of refactoring to do anyway :)

I’m also not so worried about (1) and (2) because this only concerns model generation and I hope that (1) should be really rare if not impossible with our current pattern networks.

Would that be the easiest/fastest fix for the moment?

Cheers and thanks,
Tony

**Comment by gervarro** [comment] 2017-11-20 00:20
Hi Tony,

> When we eventually have tests that fail due to (1) or (2) then we’ll think of something. The general solution will require a batch interpreter as you say as the set of detached attribute constraints can be arbitrarily complex and require a search plan.

If the attribute constraints are not detached then the incremental engine should do the job (except for extreme cases), however, if they are clearly detached, then I have the expectation that the tests will fail due to (1) or (2), and that is why I recommended to handle these cases in the green pattern.

Btw. I committed a change that should handle detached attribute constraints according to the cross-join semantics. Tomorrow I will try to prepare a new update site for Democles with the fixes for the other 2-3 tickets.

Bests,
Greg

**Closed as completed** 2018-01-21 17:38 UTC
Labels: bug, High Prio
