### ISSUE TITLE
IndexOutOfBounds Exception in ReteSearchPlanAlgorithmSession->SearchPlan->UnionFind

### ISSUE THREAD

**Issue by Arikae** [eMoflon/emoflon-ibex#246] opened 2017-10-17 14:53 UTC
Which test to execute? -> FamiliesToPersons_MA_CCTestCase.testEmptyFamily

---

What happens? -> java.lang.IndexOutOfBoundsException: Only elements from the [0,6] interval is allowed

---

The tgg constraint which triggers this exception looks like this: (Daugther2Female.tgg)
#attributeConditions {
	concat(", ", daughter.name, family.name, femalePerson.name)
}

All 4 elements are bound because we execute CC (link creation).

What happens now is that while creating the Retenetwork the algorithm expects 8 variables.
First we have 4 nodes (family, personReg, daughter, femalePerson).
Then we have 3 variables for each attribut (daugther.name, family.name, femalePerson.name)
The last variable is the constant ", ".

When performing actual pattern matching the constant is no longer considered a variable and the framesize is 7 instead of 8.
This means that the indices for the local variables are no longer 4-7 but 3-6; however, the algorithm tries to access 4-7 which then leads to the IndexOutOfBoundsException.

---

How did I debug this? 
Building of the network: I put a Conditional Breakpoint into the Constructor of ConstraintComponent checking for "constraintType instanceof org.emoflon.ibex.tgg.runtime.engine.csp.nativeOps.TGGConstraintType"
Then I used the stacktrace to find the spot where "parameters" are defined.
There I saw that constant is handled as a normal variable.

For pattern matching: Simple breakpoint for IndexOutOfBoundsException. In ReteSearchPlanAlgorithmSession we can see that the body (probably) has incorrect variables (4-7).
The least I can say is that the framesize and the variables do no longer match.

---

The complete stacktrace is:
```
java.lang.IndexOutOfBoundsException: Only elements from the [0,6] interval is allowed
	at org.gervarro.util.UnionFind.checkIndex(UnionFind.java:78)
	at org.gervarro.util.UnionFind.find(UnionFind.java:46)
	at org.gervarro.util.UnionFind.union(UnionFind.java:56)
	at org.gervarro.democles.plan.incremental.leaf.SearchPlan.isCompound(SearchPlan.java:137)
	at org.gervarro.democles.plan.incremental.leaf.SearchPlan.isCrossJoinEnabled(SearchPlan.java:112)
	at org.gervarro.democles.plan.incremental.leaf.ReteSearchPlanAlgorithmSession.run(ReteSearchPlanAlgorithmSession.java:57)
	at org.gervarro.democles.interpreter.incremental.rete.RetePatternMatcherModule.getSession(RetePatternMatcherModule.java:104)
	at org.emoflon.ibex.tgg.runtime.engine.DemoclesEngine.createAndRegisterPatterns(DemoclesEngine.java:160)
	at org.emoflon.ibex.tgg.runtime.engine.DemoclesEngine.initialise(DemoclesEngine.java:134)
	at org.emoflon.ibex.tgg.operational.OperationalStrategy.initialiseEngine(OperationalStrategy.java:168)
	at org.emoflon.ibex.tgg.operational.OperationalStrategy.registerPatternMatchingEngine(OperationalStrategy.java:108)
	at org.emoflon.ibex.tgg.run.familiestopersons_ma.CC_App.<init>(CC_App.java:30)
	at testsuite.ibex.FamiliesToPersons_MA.cc.FamiliesToPersons_MA_CCTestCase.createGenerator(FamiliesToPersons_MA_CCTestCase.java:12)
	at testsuite.ibex.FamiliesToPersons_MA.cc.TestSimplePositive.testEmptyFamily(TestSimplePositive.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)


```

**Comment by gervarro** [comment] 2017-10-30 08:25
Hi,

yesterday I quickly checked the reported issues, and I noticed the following line, which is most probably a configuration error:
https://github.com/eMoflon/emoflon-ibex-democles/blob/9fb9a9726e2d11ed0c886100257723a1de75ba5a/org.emoflon.ibex.tgg.runtime.democles/src/org/emoflon/ibex/tgg/runtime/engine/DemoclesEngine.java#L484-L485

The `org.gervarro.democles.plan.incremental.builder.AdornedNativeOperationDrivenComponentBuilder` returns `VariableComponent` and `ConstraintComponent` at runtime, which should be avoided as `FilterComponent` are the proper components in this context. (Note: `FilterComponents` are always executed before the others.) If the already existing `org.gervarro.democles.plan.incremental.builder.FilterComponentBuilder` implementation does not support your scenario, then prepare a new component builder that fits for your case.

Bests ,
Greg

**Comment by Arikae** [comment] 2017-10-30 10:46
Hi Greg,

maybe then we misunderstood something but we didn't see a way to encode the different possible adornment configurations except by using AdornedNativeOperations.
Additionally, we saw that we cannot create new data frames with FilterComponents which seems essential.
How could we do the same with FilterComponents and how are free variables bound then?

Cheers,
Lars

**Comment by anthonyanjorin** [comment] 2017-10-30 10:51
We could also do both:  create filter components for all BB* cases, and adorned native operations for all other cases.  Is this perhaps what is expected?

**Comment by gervarro** [comment] 2017-10-30 15:13
Hi,

sorry, I was too imprecise. Use a `FilterComponent` for each `AdornedNativeOperation` independently of adornment configurations. (`AdornedOperations` and `(Filter|Constraint|Variable)Components` are independent concepts. AdornedOperation defines the batch behaviour, and components influence the construction of the incremental Rete network.) The restriction that a `FilterComponent` is only available for the all `BB*` cases is defined in the `org.gervarro.democles.plan.incremental.builder.FilterComponentBuilder` class. If you copy-paste this class without the `adornedOperation.getPrecondition().cardinality() == 0` condition, then you can use this new class for your case (`TGGConstraintType`)

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-10-30 17:07
Hi Greg,

ok this doesn't seem to be working:

I implemented our own FilterComponentBuilder and used it as follows:

`private void addComponentForTGGAttributeConstraints(final TGGAttributeConstraintOperationBuilder<VariableRuntime> tggAttrConstrOpModule, final ReteSearchPlanAlgorithm algorithm, Adornment adornment) {
		algorithm.addComponentBuilder(new TGGConstraintFilterComponentBuilder<VariableRuntime>(tggAttrConstrOpModule, adornment));
	}`

The important method in the FilterComponentBuilder is as follows:

`@Override
	public final Component getConstraintOperation(final ConstraintType constraint, final List<? extends VR> parameters) {
		final NativeOperation adornedOperation = operationBuilder.getConstraintOperation(constraint, parameters);
		if (adornedOperation != null) {
			return new FilterComponent(adornedOperation, adornment, constraint, parameters);
		}
		
		return null;
	}`

This means I pass a NativeOperation to the FilterComponent.  Everything compiles.

At runtime there is a ClassCastException, however, due to a nasty cast in FilterComponent:

`InterpretableAdornedOperation getRoot() {
		return (InterpretableAdornedOperation) super.getRoot();
	}`

This code implies that FilterComponent can only work for InterpretableAdornedOperations.
Replacing FilterComponent does not seem to be an option as it is used deep in Democles.

Are we supposed to implement InterpretableAdornedOperations for all NativeOperations?  Or somehow wrap a NativeOperation with a fixed adornment to yield a suitable InterpretableAdornedOperation?

At this point I really don't understand anything at all :)

**Comment by anthonyanjorin** [comment] 2017-10-30 17:38
Hmm...  that actually worked, I just implemented an InterpretableAdornedOp that delegates to a NativeOp for a fixed adornment.  Unfortunately I now get a „No valid search plan exception“ for all cases :(

**Comment by anthonyanjorin** [comment] 2017-10-30 20:08
Hi Greg, Lars,

after some trial and error, I think I have now implemented a FilterComponentBuilder as Greg suggested and added a FilterComponent for every AdornedNativeOperation.  

Unfortunately we now get a "no valid search plan is available" Exception in almost all cases.
When debugging I can see that the FilterComponents are added (properly I hope!), but during the searchplan generation only the components for BB* actually get invoked.

@gervarro: Perhaps the assumption that FilterComponents are only defined for BB* is a bit more widespread than you think?

In any case I have pushed and you can take a look now.  

Cheers and thanks,
Tony

**Comment by gervarro** [comment] 2017-10-31 09:23
Hi,

I am going to check the situation, as I am also not quite sure what should work properly.

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-10-31 09:40
In case this helps:  after debugging a bit I have found that multiple filter component builders are registered correctly for every adornment, but PatternMatcherModule.lookupAdornedConstraintOperations goes through the list of builders and simply returns the first result that is not null.  So only one of the builders (typically BB* because that is first in the list) is queried and all other options are then missing (resulting in no valid search plan in most cases).

So the mismatch/problem is that we have multiple operation builders for the same constraint type (e.g., eq_str) but different adornments.  This doesn't seem to fit to PatternMatcherModule.lookupAdornedConstraintOperations.

Cheers and thanks,
Tony

**Comment by Arikae** [comment] 2017-11-08 10:17
Hi Greg,

any news on this issue?
Do you think this is a problem of our specification or some issue of democles itself?
Can we support you somehow? 

Cheers,
Lars

**Comment by gervarro** [comment] 2017-11-10 22:52
Hi Lars,

this specific case is a bug in Democles, as this additional compoundness analysis (based on the union-find data structure) is completely new to speed-up the search plan generation in simple cases. I might have fixed the bug yesterday, but I cannot really test it, as I have problems with the Ibex developer workspace. I also updated the `TGGConstraintFilterComponentBuilder` implementation. Could you please build a new update site for Ibex?

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-11-11 08:12
Hi Greg,

I just took a look at your fix for our FilterComponentBuilder.  Isn’t it a bit strange that you just return the filter component for the very first adorned operation?  Does this mean that any adorned operation is ok?  And only one is enough?  Or do you assume that the first adorned operation is always BB*?

**Comment by gervarro** [comment] 2017-11-15 17:05
Hi Tony,

I had some time to have a look at the complete process in details. Unfortunately I mixed up two different concepts, which resulted in a situation that my previous description was more or less correct, but the corresponding class names were not. The standard adornment configuration has to be carried out for the batch operations, while the Rete network construction process needs a single `FilterComponent` with a BB* adornment for a `NativeOperation` (i.e., the one without adornment). The batch adorned operations should not appear in this process as they are looked up later in the process, when needed.

Could you please build a new update site for Ibex again?

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-11-15 22:05
I believe @Arikae has updated the update site in the dropbox location.

Cheers,
Tony

**Comment by gervarro** [comment] 2017-11-22 23:45
The latest fixes are now available on the 2 update sites. Please check which issues have been actually resolved as I have a relatively chaotic Ibex installation now.

Bests,
Greg

**Comment by Arikae** [comment] 2017-11-23 16:02
Nice. I'm on it.

Cheers,
Lars

**Comment by Arikae** [comment] 2017-11-24 18:34
Ok, I just debugged the ArrayIndexOutOfBoundsException.

Example: 
testsuite.ibex.BenchmarxFamiliesToPersons.sync.BatchBwdEANdP - testCreatedMalePersonAsSon

What's happening? 
ArrayIndexOutofBoundsException : 13

Problematic Retepattern: 
FatherOfExistingFamilyToMale__CONSISTENCY/8

What's the reason for the exception?
We have 8 elements in the signature and 4 local variables. Additionally, we have 2 constants.
the local variables have parameter.indices [13, 8, 11, 9].
Now, adornments are not including constants which means that democles tries to access index 13 for an array of size 11 -> Exception

Not sure if this is intended but I guess the problematic operation may be the "setBody"-method in RemappedOperationComponent. (line 36 - //ignore constants)

Cheers,
Lars

**Comment by Arikae** [comment] 2017-12-04 14:16
Hi Greg,

did you have time to reproduce this?
Do you think my perception of the problem is correct?
I was a bit confused about how this could work in general when constants get indices that are not always used.

Cheers,
Lars

**Comment by gervarro** [comment] 2017-12-07 21:28
Hi,

sorry for the long delay, but I had to reinstall Eclipse and fix the plugin installation in my Ibex-Democles workspace.

This is a bug, which I already fixed in 2 lines, however, while analyzing the situation, I recognized that the current solution for the TGG attribute handling has to be reconsidered again. My questions regarding the relationship of `F*` adornments and your special disjoint patterns:
- Is `F*` the only adornment for which disjoint patterns are allowed?
- Is an operation with `F*` always disjoint? (Or do you want to assign values to variables that are connected to other parts of the pattern?)
- Can only the binary `FF` adornment be disjoint? If not (i.e., generic n-ary operations), which adornments are allowed in disjoint patterns? E.g., do you want to use `concat/4` operation with `FFFF` adornment? How can those operations/adornments identified that can be used in disjoint patterns?
- Can we say that `F*` is globally allowed for all TGG attribute constraints in `GEN` case but never in `SYNC` case (or vice versa)?

My current plan would be to enforce filtering for operations that contain at least one `B` in the adornment, and allow cross-joins for `F*` cases. This would mean that if `F*` is not allowed, then the TGG attribute operation has to be connected to the pattern and occur in the search plan with an allowed adornment. If `F*` adornment is allowed, then the corresponding operation could only be used in a disjoint pattern, and the cross-join of the disjoint subpatterns is only executed in the end (as late as possible), however, if a non-`F*` operation can be used at any point in time, then this would be preferred over the cross-join caused by the `F*` operation. Would this be OK?

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-12-08 08:05
Hi Greg,

You’ve convinced me that we should analyse and separate all attribute constraints that are „green“ and are not connected in any way with the rest of the black pattern.  

So my suggestion is that we stick to this:  in any pattern the pattern matcher receives, all attribute constraints will be directly or indirectly connected and dependent on the structural part of the pattern.  This implies trivially that there will never be any FF* adornments in the black pattern.

@Arikae and I will take care of the green part (which we have to do anyway due to axioms, i.e., completely green rules).

Would that clear up all questions?

Cheers,
Tony

**Comment by gervarro** [comment] 2017-12-09 23:41
Hi,

I published a new version on the update sites that should fix the bug, and hopefully handles non-`F*` cases correctly. There is also a `TGGFilterComponent` that performs filtering in case of non-`F*` adornment, and performs a cross-join in case of disjoint patterns. The current configuration in `TGGConstraintComponentBuilder` uses the first strategy. If you need the second one, then replace `FilterComponent` with `TGGFilterComponent`.

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-12-10 19:45
Hi Greg,

I just tested the latest version of Democles.

Were all the tests green for you?  These are my results:

- Some (but not all) cc tests are green (all BB* cases)
- *All* other tests for TGGs with CSPs are red (failing) due to a Runtime Exception "No valid search plan available".

While I might expect and understand this for some gen tests (FF*), almost (if not all) all sync tests do not have this problem.  Yes some attribute constraints will have to use adornments mixing F and B, but there should be no case of FF* adornments (i.e., the patterns should not be disjoint).

What can we do now?  The error message is rather terse and gives no hint at what exactly is causing the problem.  I can only say that it is not working (I tried switching between FilterComponent and TGGFilterComponent -- makes no difference).

Please tell us how we can support you in getting this running.

Cheers,
Tony

**Comment by gervarro** [comment] 2017-12-10 21:29
Hi Tony,

I cannot really run the developer version of Ibex, and as the latest modification affected the Democles engine configuration, I have not tested it. Could you please build me a new version of Ibex-Democles, and I am going to check what is going wrong? There might be a bug that probably affects the mixed adornment cases.

Bests,
Greg

**Comment by anthonyanjorin** [comment] 2017-12-11 10:24
Hi Greg,

I have now deployed two versions of Ibex for you in our dropbox (from Lars).  One version is with FilterComponent, the other with TGGFilterComponent.

I just tried to install both with a fresh Eclipse and this works (you might have to first enable the new update sites before they are used to automatically resolve dependencies to Democles and PlantUML).

I have also updated the PSF file in the dropbox - you only need to import it into a fresh workspace to get all tests (and pull in all repositories to get the latest from the csp-democles branch if you already have the repositories locally).

To get everything to compile you might have to select all projects and choose Clean All.
Please say if we can do anything else.

Cheers and thanks,
Tony

**Comment by gervarro** [comment] 2017-12-13 21:48
Hi Tony,

the filter component was still too specific to check (`B+`) operations. The new version, which is already published on the update sites, now produces search plans for the other cases (`BF`, `FB`, etc.). I checked the tests superficially, and I recognized the following cases/issues:
- The gen cases still frequently fail. Just tell me if there are `FF` cases that the pattern matcher should handle.
- Several tests fail with valid search plans due to the fact that the TGG attribute operations (i.e., subclasses of `TGGAttributeNativeOperation`) are currently stateful (and the old state is not deleted at completion), which results in cases where values from a previous execution are stored in `RuntimeTGGAttributeConstraintVariable`, and later reused in a completely wrong manner (`BF` operation is carried out as `BB` as both variables store an old value, and the values are obviously messed up). Please make the operations stateless.
- The test case `testPackageToDatabase_FWD` in the `testsuite.ibex.ClassMultiInhHier2DB_MA.sync.Batch` class produces a pattern `TransferSuperAttributes_AttributeToColumn__BWD/8`, in which string attributes are not connected to model elements in the specification. As `FF` is not allowed in sync cases, the pattern matcher reports a 'No search plan' error as the pattern is disjoint.

Tell me if you find further problematic cases where the pattern matcher has to be fixed.

Bests,
Greg

**Comment by Arikae** [comment] 2017-12-19 09:00
Alright, just fixed the issue with our stateful TGGAttributeNativeOperations.

Cheers,
Lars

**Closed as completed** 2018-01-21 17:39 UTC
Labels: bug, High Prio
